/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: (typeof import("element-plus/es"))["ElAlert"]
    ElAutocomplete: (typeof import("element-plus/es"))["ElAutocomplete"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: (typeof import("element-plus/es"))["ElOption"]
    ElSpace: (typeof import("element-plus/es"))["ElSpace"]
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    MyOrderForm: typeof import('./src/components/MyOrderForm.vue')['default']
    MyProducts: typeof import('./src/components/MyProducts.vue')['default']
  }
}
